### ISSUE TITLE
Windows 11: No error messages, no response from server

### ISSUE THREAD

**Issue by milelo** [m3tti/borkweb#10]
Babashka v1.12.194

The initial startup installation didn't report any errors.

```
bb -m core
You will be assimilated @ https://localhost:8080
```
I'm working in VSCode with Calva. Its not clear how to run a repl.

No response from https://localhost:8080

**Comment by m3tti** [comment]
Oh i see the problem already. *https*://localhost:8080 is wrong it has to be *http*:// i'll fix that in the message.

**Comment by milelo** [comment]
Thanks, well done. I've only just managed to figure it out and came back to report.

**Comment by m3tti** [comment]
Glad that you figured out and i could update the project. Hope you have a great time using it!
